// DataSyncService.idl : IDL source for DataSyncService
//

// This file will be processed by the MIDL tool to
// produce the type library (DataSyncService.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(786F2F04-1CAC-4C6E-B749-CD255482F24B),
	version(1.0),
]
library DataSyncServiceLib
{
	importlib("stdole2.tlb");
};

